spring.application.name=football-ingestion-service

spring.datasource.url=jdbc:mysql://localhost:3306/football_ai
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

api-football.base-url=https://v3.football.api-sports.io
api-football.api-key=88c855b59b343b7cf216de3d03c1ea70

football.ingestion.leagues=61,78,140,135,136
#61Ligue1
#78Bundesliga
#140Laliga
#135SerieA
#136SerieB

football.ingestion.seasons=2025

football.ingestion.cron.fixtures=0 */5 * * * *
football.ingestion.cron.standings=20 */5 * * * *
football.ingestion.cron.odds=40 */5 * * * *

#football.ingestion.cron.fixtures=0 */1 * * * *
#football.ingestion.cron.standings=0 */2 * * * *
#football.ingestion.cron.odds=0 */3 * * * *

football.ingestion.statistics-batch-size=120
football.ingestion.cron.fixture-statistics=0 */1 * * * *